name: Build

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-13']
        swift: ['5.9']
        include:
        - os: 'ubuntu-latest'
          swift: '5.4'

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - name: Build
      run: swift build
    - name: Test
      run: swift test
