name: Build

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        swift: ['5.9', '5.10', '6.0']

    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build
    - name: Test
      run: swift test
